In [1]:
import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
print(os.getcwd())
path = Path.cwd() / "data" / "volume_data_1y"
print(path)

e:\data_process
e:\data_process\data\volume_data_1y

In [ ]:
df = pd.read_parquet(path / "20260507_211049.parquet")
df = df.reset_index()

##计算20日动量
df["mom_1_month"] = (
    df.groupby("symbol")["adjClose"]
    .pct_change(20)
)

df["volume_1_month"] = (
    df.groupby("symbol")["volume"]
    .pct_change(20)
)

df = df[df["date"]=="2026-03-03"]
df = df[["symbol","date","volume_1_month","mom_1_month"]]
df.head()

df["volume_1_month"] = (df["volume_1_month"]-df["volume_1_month"].min())/(df["volume_1_month"].max() - df["volume_1_month"].min())
df["mom_1_month"] = (df["mom_1_month"]-df["mom_1_month"].min())/(df["mom_1_month"].max() - df["mom_1_month"].min())
df["mom_1_month"].corr(df["volume_1_month"])

EX = df["mom_1_month"].mean()
print(EX)

EY = df["volume_1_month"].mean()
print(EY)


EXY = (
    df["mom_1_month"] *
    df["volume_1_month"]
).mean()

print(EXY)

       symbol       date  volume_1_month  mom_1_month
120786    LOW 2026-03-03       -0.001846    -0.042200
120787    TMO 2026-03-03        0.243181    -0.126620
120788    AMD 2026-03-03        0.040696    -0.224632
120789  GOOGL 2026-03-03        0.109070    -0.116698
120790    BAC 2026-03-03        0.479962    -0.075191

       symbol       date  volume_1_month  mom_1_month
120786    LOW 2026-03-03        0.287915     0.423653
120787    TMO 2026-03-03        0.398501     0.227610
120788    AMD 2026-03-03        0.307115     0.000000
120789  GOOGL 2026-03-03        0.337974     0.250650
120790    BAC 2026-03-03        0.505365     0.347041

       symbol       date  volume_1_month  mom_1_month
120786    LOW 2026-03-03        0.287915     0.423653
120787    TMO 2026-03-03        0.398501     0.227610
120788    AMD 2026-03-03        0.307115     0.000000
120789  GOOGL 2026-03-03        0.337974     0.250650
120790    BAC 2026-03-03        0.505365     0.347041
120791  BRK-B 2026-03-03        0.403177     0.493393
120792   NFLX 2026-03-03        0.481534     0.940873
120793    ITW 2026-03-03        0.139276     0.712972
120794   ORCL 2026-03-03        0.028923     0.361352
120795   INTC 2026-03-03        0.211120     0.249985
120796   EQIX 2026-03-03        0.472934     1.000000
120797   ISRG 2026-03-03        0.226885     0.524880
120798    EOG 2026-03-03        0.282720     0.941293
120799    UPS 2026-03-03        0.089594     0.617320
120800    TGT 2026-03-03        0.507991     0.786584
120801    LMT 2026-03-03        0.328723     0.650675
120802     SO 2026-03-03        0.234769     0.768212
120803    CRM 2026-03-03        0.587212     0.358988
120804   MSFT 2026-03-03        0.245768     0.420110
120805      V 2026-03-03        0.128011     0.435776
120806    AON 2026-03-03        0.302863     0.451657
120807    WMT 2026-03-03        0.075746     0.593873
120808   AMGN 2026-03-03        0.481320     0.756994
120809    FDX 2026-03-03        0.125939     0.848766
120810    DHR 2026-03-03        0.273497     0.319989
120811   BKNG 2026-03-03        0.752342     0.082693
120812    COP 2026-03-03        0.879814     0.924486
120813    ICE 2026-03-03        0.382361     0.409052
120814     EL 2026-03-03        0.378950     0.135623
120815   GILD 2026-03-03        0.278506     0.602070
120816    MDT 2026-03-03        0.254287     0.386029
120817     PM 2026-03-03        0.314900     0.495742
120818     GE 2026-03-03        0.232685     0.712928
120819     KO 2026-03-03        0.317925     0.645185
120820    ACN 2026-03-03        0.603650     0.026302
120821   AMZN 2026-03-03        0.356529     0.194476
120822   CSCO 2026-03-03        0.117457     0.473014
120823    DUK 2026-03-03        0.215531     0.775480
120824     DE 2026-03-03        0.147853     0.901084
120825    PFE 2026-03-03        0.196601     0.514685
120826    SYK 2026-03-03        0.175712     0.625386
120827    HON 2026-03-03        0.473988     0.700203
120828    BMY 2026-03-03        0.432426     0.743302
120829    USB 2026-03-03        0.333607     0.385435
120830    CVX 2026-03-03        0.281420     0.743046
120831    XOM 2026-03-03        0.247470     0.764049
120832     CI 2026-03-03        0.475689     0.627598
120833   GOOG 2026-03-03        0.240910     0.243314
120834   COST 2026-03-03        0.195992     0.616157
120835    BLK 2026-03-03        0.645539     0.382542
120836   ABBV 2026-03-03        0.387359     0.606334
120837    MRK 2026-03-03        0.071464     0.653924
120838    HCA 2026-03-03        0.213004     0.731781
120839   ADBE 2026-03-03        0.480339     0.344425
120840    NSC 2026-03-03        0.382759     0.738458
120841    NKE 2026-03-03        0.552511     0.432177
120842     HD 2026-03-03        0.213581     0.452841
120843    RTX 2026-03-03        0.536212     0.592334
120844    ABT 2026-03-03        0.101896     0.610717
120845    NOW 2026-03-03        0.258093     0.426992
120846     MA 2026-03-03        0.249180     0.391846
120847    JPM 2026-03-03        0.308876     0.462266
120848    IBM 2026-03-03        0.523137     0.019504
120849    PGR 2026-03-03        0.151895     0.639638
120850   REGN 2026-03-03        0.252391     0.560301
120851   AVGO 2026-03-03        0.381425     0.400487
120852   META 2026-03-03        0.222727     0.352899
120853    APD 2026-03-03        0.206108     0.539245
120854    FIS 2026-03-03        0.437273     0.281074
120855  CMCSA 2026-03-03        0.229337     0.632805
120856    JNJ 2026-03-03        0.178018     0.695877
120857     VZ 2026-03-03        0.058313     0.847141
120858    DIS 2026-03-03        0.000000     0.496085
120859   AAPL 2026-03-03        0.072932     0.469916
120860    CAT 2026-03-03        0.175430     0.626755
120861    AXP 2026-03-03        0.821048     0.225395
120862     MO 2026-03-03        0.126847     0.770197
120863    ZTS 2026-03-03        0.174419     0.539948
120864    MCD 2026-03-03        0.233014     0.634629
120865   QCOM 2026-03-03        0.351906     0.301142
120866     CB 2026-03-03        0.554481     0.723476
120867    SHW 2026-03-03        0.241796     0.477634
120868    EMR 2026-03-03        0.127639     0.498284
120869    PLD 2026-03-03        0.327947     0.724186
120870     PG 2026-03-03        0.271905     0.620782
120871    UNP 2026-03-03        0.094076     0.837528
120872    LIN 2026-03-03        0.623061     0.731185
120873   SPGI 2026-03-03        1.000000     0.157945
120874    TXN 2026-03-03        0.139648     0.291056
120875      C 2026-03-03        0.443598     0.412446
120876    WFC 2026-03-03        0.457838     0.286696
120877    PEP 2026-03-03        0.044243     0.666880
120878    ADP 2026-03-03        0.628234     0.228167
120879    ETN 2026-03-03        0.171665     0.496572
120880     GS 2026-03-03        0.784725     0.327287
120881     GM 2026-03-03        0.439661     0.328845
120882   NVDA 2026-03-03        0.322246     0.452086
120883     CL 2026-03-03        0.133157     0.613202
120884   SCHW 2026-03-03        0.213992     0.309411

np.float64(-0.27591272322428034)

In [6]:
config = {		"symbol": "AAPL",
		"date": "2024-09-28",
		"fiscalYear": "2024",
		"period": "FY",
		"reportedCurrency": "USD",
		"grossProfitMargin": 0.4620634981523393,
		"ebitMargin": 0.31510222870075566,
		"ebitdaMargin": 0.3443707085043538,
		"operatingProfitMargin": 0.31510222870075566,
		"pretaxProfitMargin": 0.3157901466620635,
		"continuousOperationsProfitMargin": 0.23971255769943867,
		"netProfitMargin": 0.23971255769943867,
		"bottomLineProfitMargin": 0.23971255769943867,
		"receivablesTurnover": 5.903038811648023,
		"payablesTurnover": 3.0503480278422272,
		"inventoryTurnover": 28.870710952511665,
		"fixedAssetTurnover": 8.560310858143607,
		"assetTurnover": 1.0713874732862074,
		"currentRatio": 0.8673125765340832,
		"quickRatio": 0.8260068483831466,
		"solvencyRatio": 0.3414634938155374,
		"cashRatio": 0.16975259648963673,
		"priceToEarningsRatio": 37.287278415656736,
		"priceToEarningsGrowthRatio": -45.93792700808932,
		"forwardPriceToEarningsGrowthRatio": -45.93792700808932,
		"priceToBookRatio": 61.37243774486391,
		"priceToSalesRatio": 8.93822887866815,
		"priceToFreeCashFlowRatio": 32.12256867269569,
		"priceToOperatingCashFlowRatio": 29.55638142954995,
		"debtToAssetsRatio": 0.29215025480848267,
		"debtToEquityRatio": 1.872326602282704,
		"debtToCapitalRatio": 0.6518501763673821,
		"longTermDebtToCapitalRatio": 0.6009110021023125,
		"financialLeverageRatio": 6.408779631255487,
		"workingCapitalTurnoverRatio": -31.099932397502684,
		"operatingCashFlowRatio": 0.6704045534944896,
		"operatingCashFlowSalesRatio": 0.3024128274962599,
		"freeCashFlowOperatingCashFlowRatio": 0.9201126388959359,
		"debtServiceCoverageRatio": 5.024761722304708,
		"interestCoverageRatio": 0,
		"shortTermOperatingCashFlowCoverageRatio": 5.663777000814215,
		"operatingCashFlowCoverageRatio": 1.109022873702276,
		"capitalExpenditureCoverageRatio": 12.517624642743728,
		"dividendPaidAndCapexCoverageRatio": 4.7912969490701345,
		"dividendPayoutRatio": 0.16252026969360758,
		"dividendYield": 0.0043585983369965175,
		"dividendYieldPercentage": 0.43585983369965176,
		"revenuePerShare": 25.484914639368924,
		"netIncomePerShare": 6.109054070954992,
		"interestDebtPerShare": 6.949329249507765,
		"cashPerShare": 4.247388013764271,
		"bookValuePerShare": 3.711600978715614,
		"tangibleBookValuePerShare": 3.711600978715614,
		"shareholdersEquityPerShare": 3.711600978715614,
		"operatingCashFlowPerShare": 7.706965094592383,
		"capexPerShare": 0.6156891035281195,
		"freeCashFlowPerShare": 7.091275991064264,
		"netIncomePerEBT": 0.7590881483581001,
		"ebtPerEbit": 1.0021831580314244,
		"priceToFairValue": 61.37243774486391,
		"debtToMarketCap": 0.03050761336980449,
		"effectiveTaxRate": 0.24091185164189982,
		"enterpriseValueMultiple": 26.524727497716487
	}

In [ ]:
for i in config.keys():
    print (i)

symbol
date
fiscalYear
period
reportedCurrency
grossProfitMargin
ebitMargin
ebitdaMargin
operatingProfitMargin
pretaxProfitMargin
continuousOperationsProfitMargin
netProfitMargin
bottomLineProfitMargin
receivablesTurnover
payablesTurnover
inventoryTurnover
fixedAssetTurnover
assetTurnover
currentRatio
quickRatio
solvencyRatio
cashRatio
priceToEarningsRatio
priceToEarningsGrowthRatio
forwardPriceToEarningsGrowthRatio
priceToBookRatio
priceToSalesRatio
priceToFreeCashFlowRatio
priceToOperatingCashFlowRatio
debtToAssetsRatio
debtToEquityRatio
debtToCapitalRatio
longTermDebtToCapitalRatio
financialLeverageRatio
workingCapitalTurnoverRatio
operatingCashFlowRatio
operatingCashFlowSalesRatio
freeCashFlowOperatingCashFlowRatio
debtServiceCoverageRatio
interestCoverageRatio
shortTermOperatingCashFlowCoverageRatio
operatingCashFlowCoverageRatio
capitalExpenditureCoverageRatio
dividendPaidAndCapexCoverageRatio
dividendPayoutRatio
dividendYield
dividendYieldPercentage
revenuePerShare
netIncomePerShare
interestDebtPerShare
cashPerShare
bookValuePerShare
tangibleBookValuePerShare
shareholdersEquityPerShare
operatingCashFlowPerShare
capexPerShare
freeCashFlowPerShare
netIncomePerEBT
ebtPerEbit
priceToFairValue
debtToMarketCap
effectiveTaxRate
enterpriseValueMultiple

: